apiVersion: v1
kind: Service
metadata:
  labels:
    app: azure-vote-front
  name: azure-vote-front
spec:
  type: LoadBalancer
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    app: azure-vote-front
