apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: azure-vote-back
  name: azure-vote-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-back
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: azure-vote-back
    spec:
      containers:
        - env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
          image: unirjreyesacr.azurecr.io/redis:casopractico2
          name: azure-vote-back
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: data
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
