apiVersion: v1
kind: Service
metadata:
  labels:
    app: azure-vote-back
  name: azure-vote-back
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    app: azure-vote-back
