---
- name: "Playbook to create the prerequisites"
  hosts: unir01_webapp
  gather_facts: false
  vars_files:
    - ../env_vars.yaml
  tasks:
    - name: "crear www files"
      ansible.builtin.file:
        path: "{{ HOME_DIR }}/unir"
        state: directory        
    
    - name: "Create the httpd unir file"
      ansible.builtin.copy:
        dest: "{{ HOME_DIR }}/unir/index.html"
        content: |
          <html>
            <header>
              <title>SysAdmin.com</title>
            </header>
            <body>
              <p>caso practico 2 Unir JReyes</p>
            </body>
          </html>