- name: "Playbook to create httpd container"
  hosts: unir01_webapp
  gather_facts: yes
  vars_files:
    - ../env_vars.yaml
  tasks:   
    - name: "Allow the nginx container to run in the 80 port of the host"
      become: true
      become_user: root
      become_method: sudo
      ansible.posix.sysctl:
        name: net.ipv4.ip_unprivileged_port_start
        value: "80"
        sysctl_set: true
        reload: true
        
    - name: "Create the unir container"
      containers.podman.podman_login:
        username: "{{ ACR_USER   }}"
        password: "{{ ACR_PASS   }}"
        registry: "{{ ACR   }}"
    
    - name: "Create the unir container"
      containers.podman.podman_container:
        name: unir
        hostname: unir.petroil.dev
        image: "{{ ACR }}/httpd:casopractico2"
        recreate: true
        pull: always
        restart_policy: always
        stop_timeout: 0
        publish: 
          - 80:80
          - 443:443
        publish_all: true
        state: started